# Added to mitigate CVE-2017-8295 vulnerability
UseCanonicalName On

<VirtualHost *:80>
ServerAdmin webmaster@localhost
     ServerAdmin webmaster@localhost
    ServerName dogeboy.it
    ServerAlias www.dogeboy.it 
    DocumentRoot /var/www/dogeboy.it

    <Directory /var/www/dogeboy.it/>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    
    # Редирект всех HTTP запросов на HTTPS с www
    RewriteEngine on
    RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteRule ^(.*)$ https://www.dogeboy.it$1 [R=301,L]
    
    RewriteCond %{HTTP_HOST} ^www\. [NC]
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://www.dogeboy.it$1 [R=301,L]
RewriteCond %{SERVER_NAME} =dogeboy.it [OR]
RewriteCond %{SERVER_NAME} =www.dogeboy.it
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>



